// SPDX-FileCopyrightText: (C) 2026 dffdff2423 <dffdff2423@gmail.com>
//
// SPDX-License-Identifier: GPL-3.0-only

using System.Text;
using System.Text.Json;

using MetaModelGen.Schema;

using YamlWarrior.Common.Text;

namespace MetaModelGen;

public static class LspMetaGenerator {
    public static MetaModel? LoadModel(string path) {
        using var f = File.Open(path, FileMode.Open, FileAccess.Read, FileShare.Read);
        return JsonSerializer.Deserialize<MetaModel>(f);
    }

    public static void WriteFiles(MetaModel model, string outputDir, string ns) {
        var header = FileHeader(ns, model.MetaData.Version);

        foreach (var e in model.Enumerations) {
            var txt = header + GenerateEnum(e);
            Console.Error.WriteLine($"Generating enum `{e.Name}`");
            File.WriteAllText(Path.Combine(outputDir, $"{e.Name}.g.cs"), txt);
        }
    }

    private static string FileHeader(string ns, string ver) =>
        $$"""
        // SPDX-FileCopyrightText: (C) 2026 YamlWarrior Contributors
        //
        // SPDX-License-Identifier: MIT
        //
        // File automatically generated by the YamlWarrior "MetaModelGen" tool. Do not modify manually.
        //
        // Lsp Protocol Version: {{ver}}

        #nullable enable
        using System;
        using System.Text.Json.Serialization;

        namespace {{ns}};


        """;

    private static string GenerateEnum(Enumeration e) {
        if (e.Type.Kind != "base") throw new InvalidOperationException();

        switch (e.Type.Name) {
        case EnumerationTypeName.String:
            return $$"""
                     {{GenerateStandardDocs(e)}}
                     [JsonConverter(typeof(JsonStringEnumConverter<{{e.Name}}>))]
                     public enum {{e.Name}} {
                     {{GenerateStringEnumValues(e.Values)}}
                     }
                     """;
        case EnumerationTypeName.Integer:
            return $$"""
                     {{GenerateStandardDocs(e)}}
                     public enum {{e.Name}} : int {
                     {{GenerateNumberEnumValues(e.Values)}}
                     }
                     """;
        case EnumerationTypeName.UInteger:
            return $$"""
                     {{GenerateStandardDocs(e)}}
                     public enum {{e.Name}} : uint {
                     {{GenerateNumberEnumValues(e.Values)}}
                     }
                     """;
        default:
            throw new ArgumentOutOfRangeException();
        }
    }

    private static string GenerateNumberEnumValues(EnumerationEntry[] vals) {
        var sb = new StringBuilder();
        foreach (var e in vals) {
            sb.Append($"\n{GenerateStandardDocs(e)}\n{StringTools.EnsureCapitalized(e.Name)} = {((EnumerationEntryValue.Number)e.Value).Value},");
        }
        return StringTools.PadEachLine(sb.ToString(), 4);
    }

    private static string GenerateStringEnumValues(EnumerationEntry[] vals) {
        var sb = new StringBuilder();
        foreach (var e in vals) {
            sb.Append('\n')
                .Append(GenerateStandardDocs(e))
                .Append("\n[JsonStringEnumMemberName(\"")
                .Append(((EnumerationEntryValue.String)e.Value).Value)
                .Append("\")]\n")
                .Append($"{StringTools.EnsureCapitalized(e.Name)},\n");
        }
        return StringTools.PadEachLine(sb.ToString(), 4);
    }

    private static string GenerateStandardDocs(MetaInfoDef ty) => $$"""
                                                                    {{GenerateSummary(ty)}}
                                                                    /// <remarks>
                                                                    /// Since: {{ty.Since ?? "Initial Version"}}<br />
                                                                    ///
                                                                    /// Stability: {{GenerateStability(ty)}}<br />
                                                                    /// </remarks> {{GenerateObsolete(ty)}}
                                                                    """;

    // Ternary operators cannot be embedded into format expressions.

    private static string GenerateSummary(MetaInfoDef ty) =>
        ty.Documentation == null ? "" : $"""
                                         /// <summary>
                                         {StringTools.PrependEachLine(ty.Documentation, "/// ")}
                                         /// </summary>
                                         """;

    private static string GenerateStability(MetaInfoDef ty) =>
        ty.Proposed ? "Experimental" : ty.Deprecated != null ? "Deprecated" : "Stable";

    private static string GenerateObsolete(MetaInfoDef ty) =>
        ty.Deprecated != null ? $"\n[Obsolete(\"{ty.Deprecated}\"]" : "";

}
